fragment BlogCard on BlogPost {
  __typename
  title
  slug
  seoDescription
  publishedData
  coverImage {
    url
    title
    width
    height
  }
  tags: tagsCollection {
    items {
    ...TagData
    }
  }
}
