fragment ContentBlockData on ContentBlock {
  sys {
    id
  }
  title
  contentAlignment
  carousel: carouselCollection(limit: 10) {
    items {
      __typename
      ... on Entry {
        ... on RecordCard {
          ...RecordCardData
        }
      }
    }
  }
  slug
  bodyDescription {
    ...RichTextBody
  }
  background
  cards: cardsCollection(limit: 3) {
    items {
      ...AboutCardData
    }
  }
}
