fragment Footer on Footer {
    mainTitle
    copy
    navigationLinks: navigationLinksCollection {
        items {
        ...Link
        }
    }
    socialLinks: socialLinksCollection {
        items {
        ...Link
        }
    }
    copyright
}