fragment HomepageData on Homepage {
      label
      title
      kicker
      copy
      ctaButton: ctaButtonsCollection {
        items {
          ...CtaButtonData
        }
      }
      heroBackground {
        url
      }
      bodyContent: bodyContentCollection {
        items {
          ...ContentBlockData
        }
      }
}