query homepage($slug: String!) {
  homepageCollection(limit: 1, where: { slug: $slug }) {
    items {
      label
      title
      kicker
      copy
      ctaButton: ctaButtonsCollection {
        items {
          ...CtaButtonData
        }
      }
      heroBackground {
        url
      }
      bodyContent: bodyContentCollection {
        items {
          ...ContentBlockData
        }
      }
    }
  }
}
